import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer/Footer";
import { Roboto_Slab, Lemonada } from 'next/font/google'
import I18nProvider from "./components/I18nProvider/I18nProvider";
import LanguageLoader from "./components/LanguageLoader/LanguageLoader";
import WhatsappButtonFloat from "./components/WhatsappButtonFloat/WhatsappButtonFloat";

const roboto = Roboto_Slab({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  variable: '--font-roboto',
});

const lemonada = Lemonada({
  subsets: ['latin'],
  variable: '--font-lemonada'
})

export const metadata: Metadata = {
  title: "iWeb | Desarrollando futuro",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${roboto.variable} ${lemonada.variable} antialiased`}>
        <I18nProvider>
          <LanguageLoader> 
            <NavBar />
            {children}
            <WhatsappButtonFloat />
            <Footer />
          </LanguageLoader>
        </I18nProvider>
      </body>
    </html>
  );
}


