import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer/Footer";
import { Roboto_Slab, Lemonada } from 'next/font/google' 

const roboto = Roboto_Slab ({
  subsets: ['latin'],
  weight:['300', '400', '500','700', '900'],
  variable:'--font-roboto',
}); 

const lemonada = Lemonada ({
  subsets: ['latin'],
  variable: '--font-lemonada'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${lemonada.variable} antialiased`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
